version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"        # Porta para conexões
      - "15672:15672"      # RabbitMQ Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s        # Intervalo entre checagens
      timeout: 5s          # Timeout da checagem
      retries: 5           # Número de tentativas
      start_period: 10s    # Tempo para começar as checagens
    networks:
      - default

  # db:
  #   image: postgres:15
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: my_app_development
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - default

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - default

  app:
    image: ruby:3.2.1
    container_name: ruby_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      rabbitmq:
        condition: service_healthy # Espera o RabbitMQ ficar saudável
      redis:
        condition: service_started
      # db:
      #   condition: service_started
    environment:
      # DATABASE_URL: postgres://postgres:password@db:5432/my_app_development
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      PORT: 3001
    ports:
      - "3001:3001"
    command: bundle exec rails server -b 0.0.0.0 -p 3001
    networks:
      - default

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sidekiq
    depends_on:
      rabbitmq:
        condition: service_healthy # Espera o RabbitMQ ficar saudável
      redis:
        condition: service_started
      # db:
      #   condition: service_started
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/my_app_development
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    command: bundle exec sidekiq
    networks:
      - default

networks:
  default:
    driver: bridge
