default: &default
  adapter: postgresql
  timeout: 5000
  encoding: utf8
  reconnect: false
  database: <%= ENV['POSTGRES_DB'] %>  # Variável de ambiente para o nome do banco de dados
  username: <%= ENV['POSTGRES_USER'] %>  # Usuário do PostgreSQL
  password: <%= ENV['POSTGRES_PASSWORD'] %>  # Senha do PostgreSQL
  host: <%= ENV['POSTGRES_HOST'] %>  # Host do PostgreSQL (geralmente o nome do container do DB no Docker)
  port: <%= ENV['POSTGRES_PORT'] %>  # Porta do PostgreSQL (geralmente 5432)
  connect_timeout: 1
  reaping_frequency: 10
  prepared_statements: false
  variables:
    statement_timeout: 5s
    lock_timeout: 2s

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>_test  # Variável de ambiente para o nome do banco de dados de teste

development:
  <<: *default

production:
  <<: *default
